#Este docker-compose não gera BUILD pois não faz uso de Dockfiles,
# apenas de imagens pré-existentes
version: '3'
volumes: 
    dados:
networks: 
    my-network:
        driver: bridge
services: 
    db:
        image: postgres:9.6
        environment: 
            - POSTGRES_PASSWORD=postgres
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        expose: 
            - 5432
        networks: 
            - my-network
    app:
        image: maven:3.6.3-jdk-8
        working_dir: /restWithSpringBootUdemy
        environment: 
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
        volumes: 
            #expor local da aplicacao
            - .:/restWithSpringBootUdemy
            - ~/.m2:/root/.m2
        ports: 
            - "8080:8080"
        command: mvn clean spring-boot:run
        links: 
            - db
        depends_on: 
            - db
        networks: 
            - my-network